// 맥미니 pm2 프로세스 관리 설정 파일
const path = require('node:path');

module.exports = {
  apps: [
    {
      name: 'lol-bot',
      script: '/opt/homebrew/bin/uv',
      args: 'run python -u got_champe.py',
      interpreter: 'none',
      cwd: __dirname,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      kill_timeout: 5000,
      time: true,
      env: {
        DEV_MODE: 'false',
        PYTHONIOENCODING: 'utf-8',
      },
    },
    {
      name: 'lol-web',
      script: '/opt/homebrew/bin/uv',
      args: 'run python -u web_server.py',
      interpreter: 'none',
      cwd: __dirname,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      kill_timeout: 5000,
      time: true,
      env: {
        PYTHONIOENCODING: 'utf-8',
      },
    },
    {
      name: 'lol-bot-dev',
      script: '/opt/homebrew/bin/uv',
      args: 'run python -u got_champe.py',
      interpreter: 'none',
      cwd: __dirname,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      kill_timeout: 5000,
      time: true,
      env: {
        DEV_MODE: 'true',
        ACTIVITY_PORT: '8792',
        DISCORD_TOKEN: '',
        PYTHONIOENCODING: 'utf-8',
      },
    },
    {
      name: 'lol-web-dev',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      cwd: path.join(__dirname, 'web/activity'),
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      kill_timeout: 5000,
      time: true,
      env: {
        ACTIVITY_PROXY_TARGET: 'http://127.0.0.1:8792',
      },
    },
    {
      name: 'lol-health',
      script: '/opt/homebrew/bin/uv',
      args: 'run python -u scripts/healthcheck.py',
      interpreter: 'none',
      cwd: __dirname,
      cron_restart: '*/5 * * * *',
      autorestart: false,
      restart_delay: 5000,
      max_restarts: 20,
      kill_timeout: 5000,
      time: true,
      env: {
        PYTHONIOENCODING: 'utf-8',
      },
    },
    {
      name: 'lol-tunnel',
      script: '/opt/homebrew/bin/cloudflared',
      args: 'tunnel --config /Users/hansol/.cloudflared/lol.yml run',
      interpreter: 'none',
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      kill_timeout: 5000,
      time: true,
    },
  ],
};
